### ISSUE TITLE
Connection to dependencies via NPM

### ISSUE THREAD

**Issue by ponkyone** [meveo-org/mv-frontend#1]
**=> delete import map in index.html**
_Open index.html and delete import map lines_

**=> import NPM packages in package.json**
_Add import @meveo-org/all components lines in the file_

**=> build webapp with webpack in a docs folder**
_1. modify package.json with "start" command for dev server
_2. create "docs" folder for demo_
_2. add webpack config file_
_3. with command line npm install webpack && npm build_

**Comment by ClementBareth** [comment]
timeSpent: 2

**Comment by ponkyone** [comment]
timeSpent: 70
